### ISSUE TITLE
Add support for standard style

### ISSUE THREAD

**Issue by mikz** [codeclimate/codeclimate-eslint#75] opened 2016-02-14 10:53 UTC
https://github.com/feross/eslint-config-standard

It is quite used shared config and would be great to have it available in codeclimate.

would solve https://github.com/feross/standard/issues/238

**Comment by ahmadnassri** [comment] 2016-02-26 02:42
:+1:

**Comment by cilindrox** [comment] 2016-03-04 17:35
+1

**Comment by afeld** [comment] 2016-03-18 19:45
Dupe of https://github.com/codeclimate/codeclimate-eslint/issues/4.

**Comment by mikz** [comment] 2016-03-20 10:03
I'm not sure it is exact dupe. Airbnb shared config is included in the docker image. The standard can be as well without support for custom for shared config.

**Comment by afeld** [comment] 2016-03-20 10:16
Right, I just mean that they are also trying to use a shared config plugin (`eslint-config-nfl` in their first case), so if the ability to install custom plugins were added, the solution should work for both.

**Comment by dblandin** [comment] 2016-06-03 18:12
Hey everyone!

I'm happy to announce that Standard Style is now available in the ESLint engine (both stable and `eslint-2` channels) via vendored `eslint-config-standard` and `eslint-plugin-standard` npm packages.

Thanks for your patience and let me know if you run into any issues.

**Closed by dblandin** 2016-06-03 18:12 UTC

**Comment by tunnckoCore** [comment] 2016-09-09 01:54
@dblandin how to use it? I read the docs and still can't understand.

**Comment by deltaidea** [comment] 2016-09-17 10:32
@tunnckoCore I just tried switching to Engines, and it works out of the box for me. Didn't even add `.codeclimate.yml`. If you do have `.codeclimate.yml`, just add `eslint: enabled: true`, that worked for me too.

**Comment by tunnckoCore** [comment] 2016-09-18 19:16
you mean, it's the default checking engine? i believe that's not true, cuz i'm using standard, and codeclimate reports where standard not.

**Comment by deltaidea** [comment] 2016-09-19 20:03
You are right, I was mistaken. Turns out, when there's no config, CodeClimate uses a custom one, very close to Standard.
Opened an issue about this: codeclimate/codeclimate-eslint#130

**Comment by tunnckoCore** [comment] 2016-09-20 08:07
@deltaidea thanks! :)

In anyway, question is still the same - how to enable it.

**Comment by lipp** [comment] 2016-10-05 08:13
💯  thanks for supporting standard !
